import React from 'react';

/**
 * Static Terms of Use content for TrustFin.
 * Rendered in proper document flow (not absolute positioning).
 */
const TermsOfServiceContent = (): React.ReactNode => {
  return (
    <div className="mx-4 w-full space-y-6 text-sm font-normal leading-relaxed custom-text-black">
      <p className="text-xs custom-text-black">Last Updated: May 06, 2026</p>

      {/* Section 1 */}
      <div className="space-y-4">
        <h2 className="text-base font-medium custom-text-black">1. Introduction</h2>

        <div className="space-y-4">
          <p>
            a. The following general terms of use (&quot;Terms&quot;) govern and manage the access or use by you (&quot;Customer&quot;, &quot;you&quot;, &quot;your&quot;, &quot;user&quot;) of the domain name &apos;trustfin.ai&apos;, and its related sub-domains, sites, services, and tools (collectively, the &quot;Platform&quot;), owned, managed, and operated by Cleartrust Fintech Services Private Limited, a private limited company incorporated under the Companies Act, 2013, with its registered office at Office No S7, 2nd Floor, Pinnacle Business Park, Mahakali Caves Rd, Shanti Nagar, Andheri East, Mumbai — 400093 (&quot;TrustFin&quot;, &quot;we&quot;, &quot;us&quot;, or &quot;our&quot;).
          </p>

          <p>
            b. Please read these Terms carefully, as they contain the terms and conditions governing your use of the Platform and any content such as text, data, information, software, graphics, audio, video, or photographs that TrustFin may make available through the Platform, and any services that TrustFin may provide through the Platform.
          </p>

          <p>
            c. By accessing, browsing, or otherwise using the Platform, you are agreeing to be bound by these Terms and concluding a legally binding contract with TrustFin. Please do not access or use the Platform if you do not agree to these Terms or are unable to be bound by them. In addition, if you visit any of our Lending Partners&apos; (as defined below) websites or platforms, or arrive at our Platform through one of our Lending Partners&apos; websites or platforms, you may also be subject to the terms and conditions of such Lending Partners. As a condition of your access to and use of the Platform, you hereby agree that you will comply with all applicable laws and regulations when using the Platform.
          </p>

          <p>
            d. You should read these Terms and access and read all further linked information, if any, referred to herein, as such information contains further terms and conditions that apply to you as a user of the Platform.
          </p>

          <p>
            e. If you are unwilling or unable to be legally bound by these Terms, please do not use the Platform. You cannot accept these Terms if: (a) you are not lawfully entitled to use the Platform, or (b) you are not of legal age to form a binding agreement with TrustFin in accordance with the laws of India.
          </p>

          <p>
            f. By using the Platform, you hereby consent to the use of your information as outlined in our Privacy Policy hosted at https://trustfin.ai/privacy-policy (&quot;Privacy Policy&quot;). Please review the Privacy Policy, which additionally governs your visit to the Platform, to understand TrustFin&apos;s practices regarding the use of your information.
          </p>

          <p>
            g. TrustFin reserves the right, at its sole discretion, to change, modify, add, or remove portions of these Terms at any time, and will notify you by email or post a conspicuous notice on the Platform in the event of any material revisions. It is your sole responsibility to review the Terms periodically for updates or changes. Your continued use of the Platform following the posting of changes shall be deemed to mean that you accept and agree to the revisions made to these Terms.
          </p>
        </div>
      </div>

      {/* Section 2 */}
      <div className="space-y-4">
        <h2 className="text-base font-medium custom-text-black">2. Electronic Records</h2>

        <div className="space-y-4">
          <p>
            a. These Terms are an electronic record in terms of the Information Technology Act, 2000 and rules made thereunder. This electronic record is generated by a computer system and does not require any physical or digital signatures.
          </p>

          <p>
            b. These Terms are published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries Guidelines and Digital Media Ethics Code) Rules, 2021, which requires publishing the rules and regulations, privacy policy, and terms of use for access or usage of the Platform.
          </p>
        </div>
      </div>

      {/* Section 3 */}
      <div className="space-y-4">
        <h2 className="text-base font-medium text-black/80">3. General Terms of Our Offerings</h2>

        <div className="space-y-4">
          <p>
            a. TrustFin operates the Platform, which is an AI-powered loan marketplace that facilitates your access to information — primarily about personal loans, business loans, and other financial products or services — provided by our Lending Partners (as defined below) whilst using this Platform (&quot;Services&quot;). Through the Platform, we use an AI-driven matching engine to connect users interested in availing loans (&quot;Borrower(s)&quot;) with our non-banking financial company (&quot;NBFC&quot;) partners or banks who are authorized by the Reserve Bank of India (&quot;RBI&quot;) to offer and sanction such credit facilities on the Platform (&quot;Lending Partners&quot;), thereby facilitating provision of short-term credit facilities (&quot;Credit Facility&quot;).
          </p>

          <p>
            b. TrustFin does not engage in lending or borrowing through its Platform. All Credit Facilities are extended solely by the Lending Partners, subject to terms agreed directly between you and the Lending Partners. TrustFin merely operates the Platform to enable such interactions and has no role in the approval or disbursement of credit, which remains at the sole discretion of the respective Lending Partner. Furthermore, TrustFin is not registered with the RBI or any other statutory authority as a financial institution and does not possess any license to independently provide loans or credit facilities. It is also clarified that TrustFin is not classified as a &apos;financial institution&apos; under the Companies Act, 2013, the Banking Regulation Act, 1949, or any other laws for the time being in force in India. Additionally, TrustFin does not operate as a deposit-taking entity, chit fund, or investment scheme provider under any applicable laws or regulations in India.
          </p>

          <p>
            c. In the event you avail a Credit Facility through the Platform, following your use of the Services, the relevant Lending Partner will provide an online loan agreement for your review, accessible via the Platform. By clicking &apos;I Accept&apos;, you acknowledge that you are entering into a binding arrangement with the Lending Partner, subject to the terms outlined therein. These terms may include provisions for assessing your creditworthiness, verifying your identity, and ensuring compliance with applicable laws, including those relating to fraud prevention and anti-money laundering. Repayment of the Credit Facility must be made in accordance with the schedule specified in the loan agreement. Any default or breach of the agreement may lead to an immediate suspension of Services facilitated through the Platform, and may trigger provisions requiring immediate repayment of the outstanding amount under the Credit Facility.
          </p>

          <p>
            d. We receive a fee and/or commission from Lending Partners when you use our Services to avail a Credit Facility from them.
          </p>

          <p>
            e. TrustFin does not charge any registration, membership, or browsing fee from Borrowers. However, TrustFin reserves the absolute right to introduce such fees at any time. All such fees will be communicated to users by posting them on the Platform and shall become effective immediately after they are posted. All fees charged by TrustFin shall be in Indian Rupees. Your continued use of TrustFin shall be deemed as acceptance of the amended provisions of the Terms from time to time.
          </p>
        </div>
      </div>

      {/* Section 4 */}
      <div className="space-y-4">
        <h2 className="text-base font-medium text-black/80">4. Membership Eligibility</h2>

        <p>
          Use and access of this Platform is strictly available only to persons who can enter into legally binding contracts under the Indian Contract Act, 1872 and who are not barred from receiving Services under the laws of India or other applicable jurisdictions. Persons who are &apos;incompetent to contract&apos; within the meaning of the Indian Contract Act, 1872 — including minors, un-discharged insolvents, and persons of unsound mind — are not eligible to use the Platform. Any person under the age of 18 (eighteen) shall neither register on the Platform, nor avail the Services, nor transact on the Platform for any reason whatsoever. TrustFin reserves the right to terminate any person&apos;s membership and/or refuse access to the Platform if it is discovered that such person is not eligible to use the Platform.
        </p>
      </div>

      {/* Section 5 */}
      <div className="space-y-4">
        <h2 className="text-base font-medium text-black/80">5. Opening of Account on Platform</h2>

        <div className="space-y-4">
          <p>
            a. In order to use the Platform holistically and to avail the Services, you will have to create an account by signing up on the Platform (&quot;Account&quot;), which can be done by providing or using the following:
          </p>

          <div className="space-y-2 pl-4">
            <p>(i) your cell phone number with password; or</p>
            <p>(ii) email address with password; or</p>
            <p>(iii) such other login credentials as are adopted by the industry for setting up an account with the Platform (collectively, &quot;Login Credentials&quot;).</p>
          </div>

          <p>
            b. Upon entering the Login Credentials, you will receive a One Time Password (&quot;OTP&quot;) for the purpose of verification, or such other auto-verification process adopted by the industry. Upon completion of verification, the Account is created and is ready for use. You shall not transfer or share your Account information or Login Credentials with anyone, or create more than one Account.
          </p>

          <p>
            c. Once registered, in order to log into the Account, you will be required to use your Login Credentials. Upon successful registration on the Platform, you will be provided access to a dashboard enabling you to access your Account details.
          </p>

          <p>
            d. You shall be solely responsible for maintaining the confidentiality of your Account and the Login Credentials, and to the extent allowed by law, you hereby accept responsibility for all activities on the Account authenticated through the Login Credentials, whether authorized or not. You agree to keep Login Credentials confidential and secure, and shall not make them available, directly or indirectly, to any unauthorized individual. You acknowledge and agree that if you allow a person to gain access to your Login Credentials — with or without permission — you are authorizing that person to use the Platform through the Account, and you shall be responsible for all actions that result from such access, even if unauthorized or fraudulent. TrustFin shall not be held liable in any manner whatsoever for lack of any such authorization.
          </p>

          <p>
            e. TrustFin shall not be held liable for any loss or damage arising from your use of the Platform, theft of Login Credentials, use of the Login Credentials, release of Login Credentials to a third party, or your authorization of another person to access and use the Platform using the Account.
          </p>

          <p>
            f. In case of any misappropriation or unauthorized access of the Account, you agree to communicate the same to TrustFin immediately at care@trustfin.ai. You shall further ensure that you exit or logout from the Account at the end of each session. TrustFin shall not be liable for any loss or damage arising from your failure to comply with this provision.
          </p>

          <p>
            g. You agree that all information provided by you to TrustFin at any time (including during registration) will be true, accurate, up-to-date, and complete. If TrustFin has reasonable grounds to suspect that information is untrue, inaccurate, or incomplete, TrustFin shall have the right to indefinitely suspend, terminate, or block your Account and refuse to provide you Services.
          </p>
        </div>
      </div>

      {/* Section 6 */}
      <div className="space-y-4">
        <h2 className="text-base font-medium text-black/80">6. License and Access</h2>

        <div className="space-y-4">
          <p>
            a. TrustFin and its licensors, if any, shall be the sole and absolute owners of the Platform, including but not limited to the idea behind the Platform, the copyright in all content on the Platform, all trademarks, designs, logos, and other insignia of trade used on the Platform, including all AI-powered features and algorithms, all of which are subject to protection under patent, copyright, trademark, trade secret, and other intellectual property laws of India and other countries.
          </p>

          <p>
            b. As long as you comply with these Terms, TrustFin grants you a limited, non-transferable, and revocable license to access and use the Platform or any part thereof solely for the purpose of availing the Services, but not to download any material from it (other than page caching) or modify it or any portion of it, except with the express written consent of TrustFin and/or its affiliates. Any unauthorized access to the Platform or any attempt to modify, adapt, translate, or reverse engineer any part of the Platform, including its AI matching engine, is strictly not permitted.
          </p>

          <p>
            c. This license is non-transferable and does not permit any resale or commercial use of this Platform or its contents; any downloading or copying of account information for the benefit of anyone other than your own use; or any use of data mining, robots, scraping, or similar data gathering and extraction tools. The Platform or any portion thereof may not be reproduced, duplicated, copied, sold, resold, visited, distributed, or otherwise exploited for any commercial purpose without the express written consent of TrustFin and/or its affiliates. Any unauthorized use of the Platform shall terminate the permission or license granted by TrustFin, and TrustFin shall have the right to seek legal recourse available to it under applicable laws.
          </p>
        </div>
      </div>

      {/* Section 7 */}
      <div className="space-y-4">
        <h2 className="text-base font-medium text-black/80">7. Prohibited Uses</h2>

        <p>
          You agree, undertake, and covenant that during your use of the Platform and Services, you shall not host, display, upload, modify, publish, transmit, store, update, or share any information that:
        </p>

        <div className="space-y-2">
          <p>a. belongs to another person or entity and to which you do not have any right;</p>
          <p>b. is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, pedophilic, libelous, invasive of another person&apos;s privacy, insulting or harassing on the basis of gender, hateful or racially or ethnically objectionable, relating to or encouraging money laundering or gambling, or otherwise inconsistent or contrary to the laws in force in any manner whatsoever;</p>
          <p>c. is harmful to children;</p>
          <p>d. is misleading in any way;</p>
          <p>e. involves the transmission of &quot;junk mail&quot;, &quot;chain letters&quot;, or unsolicited mass mailing or &quot;spamming&quot;;</p>
          <p>f. infringes upon or violates any third party&apos;s rights including, but not limited to, any patent, trademark, copyright, or other proprietary rights, intellectual property rights, or rights of privacy;</p>
          <p>g. impersonates another person or provides instructional information about illegal activities such as violating someone&apos;s privacy or creating computer viruses;</p>
          <p>h. tries to gain unauthorized access to the Platform or to profiles, communities, account information, or other areas of the Platform, or solicits passwords or personally identifying information for commercial or unlawful purposes from other users;</p>
          <p>i. engages in commercial activities without TrustFin&apos;s prior written consent, such as contests, sweepstakes, barter, or advertising;</p>
          <p>j. interferes with another user&apos;s use of the Platform;</p>
          <p>k. refers to any website or URL that, in TrustFin&apos;s sole discretion, contains material that is inappropriate for the Platform or violates the spirit of these Terms;</p>
          <p>l. deceives or misleads the addressee or users about the origin of messages, or communicates any information which is patently false, misleading, grossly offensive, or menacing in nature;</p>
          <p>m. contains software viruses, trojan horses, worms, or any other computer codes or programs designed to interrupt, destroy, or limit the functionality of any computer resource or covertly steal any system, data, or personal information;</p>
          <p>n. threatens the unity, integrity, defence, security, or sovereignty of India, friendly relations with foreign states, or public order, or causes incitement to the commission of any cognisable offence; or</p>
          <p>o. violates any law for the time being in force.</p>
        </div>

        <p>Additionally, you shall not use anyone else&apos;s account at any time.</p>
      </div>

      {/* Section 8 */}
      <div className="space-y-4">
        <h2 className="text-base font-medium text-black/80">8. Rights and Reservations</h2>

        <p>TrustFin reserves the right to:</p>

        <div className="space-y-2">
          <p>a. Make all decisions in relation to your registration with TrustFin;</p>
          <p>b. Assign you a username different from the one chosen by you, if it impersonates an existing username or is otherwise inappropriate;</p>
          <p>c. Request additional documents and information from you for the purpose of your registration as a user with the Platform; and</p>
          <p>d. Deny access to the Platform or any portion thereof without notice for the following reasons: (i) any unauthorized access or use by you; (ii) attempts to assign or transfer any rights granted to you under these Terms; or (iii) violation of any of the provisions of these Terms or any applicable laws.</p>
        </div>
      </div>

      {/* Section 9 */}
      <div className="space-y-4">
        <h2 className="text-base font-medium text-black/80">9. Promotional Offers</h2>

        <p>
          TrustFin may, from time to time, announce certain offers with the intent to promote its Platform and/or Services (&quot;Promotional Offer(s)&quot;). Promotional Offers will always be governed by these Terms plus certain additional terms and conditions, if any, which will be specific to the corresponding Promotional Offer and shall prevail over these Terms to the extent of any conflict. TrustFin reserves the right to withdraw, discontinue, modify, extend, and suspend the Promotional Offers and the terms governing them, at its sole discretion. Additionally, TrustFin may from time to time offer referral bonuses and rewards to you for inviting new users to the Platform and for completing other activities on the Platform.
        </p>
      </div>

      {/* Section 10 */}
      <div className="space-y-4">
        <h2 className="text-base font-medium text-black/80">10. Users&apos; Posts and Reviews</h2>

        <div className="space-y-4">
          <p>
            a. The Platform may allow you to post certain content, data, or information belonging to you, such as reviews and ratings of products or Services, comments, and suggestions (collectively referred to as &quot;User Content&quot;).
          </p>

          <p>
            b. You, being the originator of the User Content, are responsible for all User Content that you upload, post, publish, transmit, or otherwise make available on the Platform. You represent and covenant that you have obtained all relevant consents and approvals in order to post the User Content and shall not post any content relating to or owned by a third party for the promotion or sale of such third party&apos;s products or services. By sharing or submitting any User Content, you agree that you shall be solely responsible for all such content and TrustFin shall neither be responsible nor liable for any User Content you make available on or through the Platform. TrustFin reserves the right to remove any third-party marketing material and disable access to the User Content on the Platform.
          </p>

          <p>
            c. You hereby grant TrustFin a perpetual, non-revocable, worldwide, royalty-free, and sub-licensable right and license to use, copy, distribute, display, publish, transmit, reproduce, modify, and adapt the User Content and create derivative works thereof. You represent and warrant that you own or otherwise control all of the rights to the User Content that you post, and that: (i) the User Content is accurate; (ii) use of the User Content does not breach these Terms; and (iii) such User Content is lawful.
          </p>
        </div>
      </div>

      {/* Section 11 */}
      <div className="space-y-4">
        <h2 className="text-base font-medium text-black/80">11. Links to Third-Party Websites</h2>

        <p>
          The Platform may contain or provide links to websites and resources of third parties. Since TrustFin has no control over such third-party websites and resources, you acknowledge and agree that TrustFin is not responsible for and has no liability for the functionality, actions, inactions, privacy settings, privacy policies, terms, or content of any such websites or resources. Your interaction with any third party accessed through the Platform is at your own risk and TrustFin shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods, or services. TrustFin strongly recommends that you review and understand the terms and conditions and privacy policies of each such third-party website before enabling any sharing functions or visiting such website.
        </p>
      </div>

      {/* Section 12 */}
      <div className="space-y-4">
        <h2 className="text-base font-medium text-black/80">12. Modification to Services</h2>

        <div className="space-y-4">
          <p>
            a. TrustFin reserves the right to alter or modify all or any part of its Services at any time without prior notice to the Customer. The Customer acknowledges that such modifications may be implemented to ensure compliance with new or amended legal or regulatory requirements, or to improve the AI-powered features of the Platform.
          </p>

          <p>
            b. TrustFin retains the right, at its sole discretion, to suspend, modify, or permanently discontinue any Service (or any part thereof), with or without cause. TrustFin shall not be held liable for any such changes, temporary suspensions, or discontinuations of Services.
          </p>

          <p>
            c. If any amounts for products or Services remain unpaid by you, you will remain liable to TrustFin or its partners, as the case may be, for such payment obligations.
          </p>
        </div>
      </div>

      {/* Section 13 */}
      <div className="space-y-4">
        <h2 className="text-base font-medium text-black/80">13. Disclaimer of Warranties</h2>

        <p className="font-medium uppercase text-zinc-600">
          THE PLATFORM AND ALL INFORMATION, CONTENT, MATERIALS, AI-GENERATED RECOMMENDATIONS, AND SERVICES INCLUDED ON OR OTHERWISE MADE AVAILABLE TO YOU THROUGH THE PLATFORM ARE PROVIDED BY TRUSTFIN ON AN &quot;AS IS,&quot; &quot;AS AVAILABLE&quot; BASIS, WITHOUT REPRESENTATIONS OR WARRANTIES OF ANY KIND. TRUSTFIN MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE OPERATION OF THE PLATFORM, THE ACCURACY OR COMPLETENESS OF CONTENT, AI MATCH RESULTS, OR LOAN RECOMMENDATIONS. TRUSTFIN SHALL HAVE NO RESPONSIBILITY FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY CONTENT, MATERIALS, OR INFORMATION. YOU EXPRESSLY AGREE THAT YOUR USE OF THE PLATFORM AND SERVICES IS AT YOUR OWN DISCRETION AND SOLE RISK. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM TRUSTFIN OR THROUGH THE PLATFORM SHALL CREATE ANY WARRANTY. TO THE FULLEST EXTENT PERMITTED BY LAW, TRUSTFIN DISCLAIMS ANY AND ALL REPRESENTATIONS AND WARRANTIES WITH RESPECT TO THE SERVICES, PLATFORM, AND ITS CONTENT, WHETHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, WARRANTIES OF TITLE, MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE. FURTHER, TRUSTFIN AND ITS SERVICE PROVIDERS, AFFILIATES, BUSINESS PARTNERS, AND LENDING PARTNERS MAKE NO WARRANTY THAT (I) THE SERVICES WILL MEET YOUR REQUIREMENTS, (II) THE SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, (III) THE RESULTS OBTAINED FROM THE USE OF THE SERVICES OR AI RECOMMENDATIONS WILL BE ACCURATE OR RELIABLE, (IV) THE QUALITY OF ANY PRODUCTS, SERVICES, OR INFORMATION OBTAINED BY YOU THROUGH THE SERVICES WILL MEET YOUR EXPECTATIONS, AND (V) ANY ERRORS IN THE TECHNOLOGY WILL BE CORRECTED.
        </p>
      </div>

      {/* Section 14 */}
      <div className="space-y-4">
        <h2 className="text-base font-medium text-black/80">14. Limitation of Liability</h2>

        <p className="font-medium uppercase text-zinc-600">
          IN NO EVENT SHALL TRUSTFIN, OR ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, AFFILIATES, GROUP COMPANIES, AND PARTNERS BE LIABLE FOR ANY DIRECT, SPECIAL, INCIDENTAL, INDIRECT, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, OR LOSS OF PROFIT OR REVENUES WHATSOEVER RESULTING FROM ANY SERVICES OR CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE PLATFORM, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT TRUSTFIN IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. TRUSTFIN SHALL NOT BE LIABLE UNDER ANY CIRCUMSTANCES FOR DAMAGES HOWSOEVER ARISING OUT OF OR IN ANY WAY RELATED TO PRODUCTS, SERVICES, CREDIT FACILITIES, AI-GENERATED LOAN MATCHES, AND/OR INFORMATION OFFERED OR PROVIDED BY THIRD PARTIES, INCLUDING THE LENDING PARTNERS, THROUGH THE PLATFORM.
        </p>
      </div>

      {/* Section 15 */}
      <div className="space-y-4">
        <h2 className="text-base font-medium text-black/80">15. Indemnification</h2>

        <p>
          You shall indemnify and hold TrustFin, its licensees, directors, employees, officers, affiliates, subsidiaries, representatives, Lending Partners, and group companies (as applicable) and their respective officers, directors, agents, and employees harmless from any and all claims, demands, or actions, including reasonable attorneys&apos; fees, made by any third party or penalty imposed due to or arising out of your breach of these Terms or your violation of any law, rules, or regulations.
        </p>
      </div>

      {/* Section 16 */}
      <div className="space-y-4">
        <h2 className="text-base font-medium text-black/80">16. Termination of Access to the Platform</h2>

        <div className="space-y-4">
          <p>a. Your Account can be terminated at any time by:</p>

          <div className="space-y-2 pl-4">
            <p>i. You, by ceasing to use the Platform.</p>
            <p>ii. TrustFin, in its sole discretion for any reason or no reason, including your violation of these Terms, or lack of use of the Platform. You acknowledge that termination of access to the Platform may be effected without any prior notice, and TrustFin may immediately deactivate or delete the Account and all related information and/or bar any further access to the Account or the Services.</p>
          </div>

          <p>
            b. If you are a Borrower using the Platform, you are prohibited from deleting your Account if there remain any outstanding repayment obligations under the Credit Facility, as stipulated in your loan agreement with the Lending Partner. Deleting your Account before fulfilling complete repayment obligations shall not absolve you from your contractual obligation to pay such outstanding amounts to the Lending Partner.
          </p>
        </div>
      </div>

      {/* Section 17 */}
      <div className="space-y-4">
        <h2 className="text-base font-medium text-black/80">17. Takedown Policy</h2>

        <div className="space-y-4">
          <p>
            a. If you identify any content on the Platform that you believe violates TrustFin&apos;s policies or applicable law, please notify TrustFin&apos;s Grievance Officer at care@trustfin.ai. In your notification, you must include the following details:
          </p>

          <div className="space-y-2 pl-4">
            <p>i. Your name, email ID, phone number, and postal address;</p>
            <p>ii. A precise description of the content in question along with its specific location on the Platform (including the relevant web page); and</p>
            <p>iii. A detailed explanation of why you deem the content objectionable.</p>
          </div>

          <p>
            b. Upon receipt of your notice, we will review the details provided and may take appropriate action in accordance with our policies and applicable law, which could involve requesting additional information from you or removing the identified content.
          </p>
        </div>
      </div>

      {/* Section 18 */}
      <div className="space-y-4">
        <h2 className="text-base font-medium text-black/80">18. Miscellaneous</h2>

        <div className="space-y-4">
          <p>
            a. Assignment: TrustFin reserves the right, at its own discretion, to freely assign and transfer the rights and obligations under these Terms to any third party.
          </p>

          <p>
            b. Governing Law and Jurisdiction: These Terms shall be governed by and interpreted and construed in accordance with the laws of India, and any dispute concerning these Terms shall be subject to the exclusive jurisdiction of the appropriate courts at Mumbai, India.
          </p>

          <p>
            c. Severability and Waiver: These Terms, the Privacy Policy, and other referenced material herein or on the Platform, constitute the entire agreement between you and TrustFin with respect to the products or Services offered on the Platform and supersede all prior or contemporaneous communications and proposals (whether oral, written, or electronic) between you and TrustFin with respect thereto. If any provision of the Terms is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that the Terms will otherwise remain in full force and effect and enforceable.
          </p>
        </div>
      </div>

      {/* Section 19 */}
      <div className="space-y-4">
        <h2 className="text-base font-medium text-black/80">19. Grievance Redressal Mechanism</h2>

        <div className="space-y-4">
          <p>
            In accordance with the Information Technology Act, 2000 and Rules made thereunder, the name and contact details of the Grievance Officer are provided below:
          </p>

          <p className="font-medium text-zinc-700">a. With respect to the Terms:</p>

          <div className="space-y-2">
            <p>Name: Abhay Padoor (Sample — replace with authorized officer)</p>
            <p>
              Address: Office No S7, 2nd Floor, Pinnacle Business Park, Mahakali Caves Rd, Shanti Nagar, Andheri East, Mumbai — 400093 (Sample — replace with TrustFin&apos;s registered address)
            </p>
            <p>Cell: +91 9240249293 (Sample — replace with official number)</p>
            <p>Email: care@trustfin.ai</p>
          </div>

          <p>
            The TrustFin Grievance Officer can be contacted between 10:00 a.m. to 6:00 p.m. from Monday to Friday, except on public holidays.
          </p>

          <p>
            We shall respond to your request(s) or grievance within twenty-four (24) hours from the time of receipt. In the event that we are unable to acknowledge or provide a response within the stipulated timeframe for any reason, we shall duly notify you accordingly.
          </p>

          <p className="font-medium text-zinc-700">b. With respect to any Lending Partners:</p>

          <p>
            If the grievance is not resolved by the TrustFin Grievance Officer within 30 (thirty) days of lodging the grievance, or if the User is not satisfied with the response received from TrustFin, such User may approach the relevant Lending Partner to have the grievance resolved. The grievance redressal mechanism of the Lending Partner is accessible at: https://trustfin.ai/lending-partners. In case you are not satisfied with the resolution provided by us or the Lending Partners, you may submit your grievance at the RBI Sachet Portal.
          </p>
        </div>
      </div>

      {/* Section 20 */}
      <div className="space-y-4">
        <h2 className="text-base font-medium text-black/80">20. How to Contact TrustFin</h2>

        <p>If you have questions or concerns about these Terms, please contact us at:</p>

        <div className="space-y-2">
          <p>Email: care@trustfin.ai</p>
          <p>Website: https://trustfin.ai/</p>
        </div>
      </div>

      <p className="border-t border-zinc-200 pt-6 text-xs text-zinc-400">
        © 2026 Cleartrust Fintech Services Private Limited. All rights reserved. TrustFin.ai is a product of Cleartrust Fintech Services Private Limited.
      </p>
    </div>
  );
};

export default TermsOfServiceContent;
