export const AI_CHAT_COPY = {
  title: 'Finn — AI Loan Assistant',
  onlineStatus: 'Online now',
  secureProcessing: 'SECURE AI PROCESSING',
  guestWelcomeTitle: 'Welcome to Trustfin',
  guestWelcomeSubtitle: "Ask anything about loans — we'll help you find the best offer.",
  guestWelcomeCta: 'You can start chatting now.',
  fallbackPlaceholder: 'Ask anything about your loan options...',
  chipsPlaceholder: 'Tap a chip above...',
  loadingMessage: 'Loading your chat...',
  typingMessage: 'Finn is typing...',
  historyRefreshErrorMessage: "Couldn't refresh chat. Please try again.",
  genericError: 'Something went wrong. Please try again.',
  completedMessage: 'Thanks! We are matching your best offer now.',
  escalateMessage: 'I am connecting you to a specialist for further support.',
} as const;
