export const AI_CHAT_COPY = {
  title: 'Finn — AI Loan Assistant',
  onlineStatus: 'Online now',
  secureProcessing: 'SECURE AI PROCESSING',
  guestWelcomeMessage: 'Hi! I can help you compare loan options. Sign in when you are ready to continue.',
  fallbackPlaceholder: 'Ask anything about your loan options...',
  chipsPlaceholder: 'Tap a chip above...',
  loadingMessage: 'Loading your chat...',
  typingMessage: 'Finn is typing...',
  historyRefreshErrorMessage: "Couldn't refresh chat. Please try again.",
  loginTitle: 'Continue with your mobile number',
  loginSubtitle: 'Log in once to keep your chat secure and personalized.',
  loginWithPendingMessageSubtitle: 'We saved your message. Verify OTP and we will send it automatically.',
  loginContinueLabel: 'Send OTP',
  loginSendingOtpLabel: 'Sending OTP...',
  loginVerifyLabel: 'Verify & Continue',
  loginVerifyingLabel: 'Verifying...',
  genericError: 'Something went wrong. Please try again.',
  completedMessage: 'Thanks! We are matching your best offer now.',
  escalateMessage: 'I am connecting you to a specialist for further support.',
} as const;
