export const AI_CHAT_COPY = {
  title: 'Finn — AI Loan Assistant',
  onlineStatus: 'Online now',
  secureProcessing: 'SECURE AI PROCESSING',
  guestWelcomeMessage: 'Hi! Please enter your mobile number to continue.',
  loginOtpPrompt: 'Thanks! We sent an OTP to {phone}. Please enter it to continue.',
  loginPhoneInvalid: 'Please enter a valid 10-digit mobile number.',
  loginOtpInvalid: 'Please enter a valid 6-digit OTP.',
  loginPhonePlaceholder: 'Enter 10-digit mobile number',
  loginOtpPlaceholder: 'Enter 6-digit OTP',
  fallbackPlaceholder: 'Ask anything about your loan options...',
  chipsPlaceholder: 'Tap a chip above...',
  loadingMessage: 'Loading your chat...',
  typingMessage: 'Finn is typing...',
  historyRefreshErrorMessage: "Couldn't refresh chat. Please try again.",
  genericError: 'Something went wrong. Please try again.',
  completedMessage: 'Thanks! We are matching your best offer now.',
  escalateMessage: 'I am connecting you to a specialist for further support.',
} as const;
